### ISSUE TITLE
Problem with com.ibh.systems.neoscada.iec104slave

### ISSUE THREAD

**Issue by sharkwinter** [ibh-systems/neoscada-misc#1]
@CptMauli 
The following error occurred when running iec104slave:

[ com.ibh.systems.neoscada.iec104slave]$ java -classpath target/com.ibh.systems.neoscada.iec104slave-0.0.1-SNAPSHOT.jar com.ibh.systems.neoscada.iec104example.TestSlave
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/openscada/protocol/iec60870/server/data/DataModel
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.openscada.protocol.iec60870.server.data.DataModel
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more

**Comment by CptMauli** [comment]
Sorry, I just saw the issue right now.

please make yourself familiar how classpaths work in Java, e.g. look here: http://javapapers.com/java/java-classpath/ or here: https://stackoverflow.com/questions/219585/setting-multiple-jars-in-java-classpath

To run the jar file, you'll have to add all the jar files which are parts of the dependencies. This is quite a bit.

To your benefit, I updated the example to use Eclipse NeoSCADA 0.4.0 (this is when we migrated the iec library back to the Eclipse Foundation) instead of openSCADA.

I also added the maven shade plugin, which creates a runnable jar file.

**Comment by sharkwinter** [comment]
Thank you very much @CptMauli
